[WIP]EC2,ALB,SGVをコード化
Michiko-Ito20/CFn20240626 pull request #2
Opened 2024-07-10 13:54 UTC by Michiko-Ito20

EC2とALBとSGVをコード化しました。

2024-08-24 08:34 UTC, MasatoshiMizumoto requested changes
コメント入れました！

2024-08-24 08:34 UTC, MasatoshiMizumoto commented on S3test2406.yml
> +
InstanceProfileは別のファイルにも記述がありますが、両方必要でしょうか？
必要ならファイルを分けている理由などもください！

※デプロイできるテンプレートが作れたことと、不要な記述が含まれていないかはイコールではないので、そこは精査する仕組みを考えないとです！

2024-08-24 08:34 UTC, MasatoshiMizumoto commented on RDStest2406.yml
ＯＫ

2024-08-24 08:34 UTC, MasatoshiMizumoto commented on EC2,ALB,SG2406.yml
ＯＫ

2024-08-24 08:34 UTC, MasatoshiMizumoto commented on VPCtest2406.yml
ＯＫ

2024-08-26 14:05 UTC, MasatoshiMizumoto requested changes
コメントいれました！

2024-08-26 14:05 UTC, MasatoshiMizumoto commented on S3test2406.yml
EC2とInstance Profile,Role,Policyの関係性を説明したと思いますが、この課題で提出したテンプレートをデプロイしたとき、それぞれの数はいくつ（N:N:N）で、その想定はご自身の考え方とあってますか？？

2024-08-27 07:56 UTC, Michiko-Ito20 commented on S3test2406.yml
前回の構築をCloudFormationで実現という課題なので、Instance１つにProfile1つ、RoleとPolicyも1つずつという事で合ってると思ってます。

2024-08-28 12:05 UTC, MasatoshiMizumoto commented on S3test2406.yml
> +      Path: "/"                                 #パスを指定
これをEC2テンプレート側のRoleに

2024-08-28 12:06 UTC, MasatoshiMizumoto commented on S3test2406.yml
> +        - !Ref S3AccessRole                       #S3アクセスを参照
これをEC2テンプレート側に挿入で行ける気がします

2024-10-27 04:54 UTC, MasatoshiMizumoto commented
このPRでの議論は終わって別対応をしているのでクローズとする

2024-10-27 04:54 UTC, closed without merging