CFnTraining用の提出です。
Michiko-Ito20/CFn20240626 pull request #4
Opened 2024-11-17 13:42 UTC by Michiko-Ito20

CFnTraining用に提示された課題を提出します。
CloudTrailとConfigを設定すると理解しました。
よろしくお願いいたします。

2024-11-18 01:46 UTC, MasatoshiMizumoto commented
過去の課題の差分が含まれているので、解消対応を先に一緒にやりましょう！
一旦このままマージ無しでクローズします！

2024-11-18 11:05 UTC, MasatoshiMizumoto requested changes
拝見しました！
パッと見は記述におかしな点は見当たらないので、以下をお願いします。結果報告のエビデンスを拝見したのち、承認としたいです。

- [ ] 設計書とコードを見比べて、typoや見逃しが無いか確認した。
- [ ] 実際にデプロイして、動作することを確認した

2024-11-18 11:05 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +  CloudTrailBucketPolicy:
この位置にあるのがスッキリしないなと思いました！

2024-11-18 11:05 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +Description: "AWS CloudTrail S3 Bucket Policy"
中身と合ってない気がします！

2025-01-06 13:06 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +    Type: 'AWS::S3::Bucket'
設計にある「パブリックアクセス設定」は記述しなくても大丈夫でしたか？

2025-01-10 14:53 UTC, Michiko-Ito20 commented on CFn_training20241031/Training20241113.yml
> +    Type: 'AWS::S3::Bucket'
修正しているうちに抜けてしまったようです。失礼いたしました。

2025-01-10 14:54 UTC, Michiko-Ito20 commented on CFn_training20241031/Training20241113.yml
> +        {
Fn::Subへ変更いたしました

2025-01-10 15:05 UTC, Michiko-Ito20 commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
デフォルト値はnullです。[# DestinationBucketName: !Ref 'AWS::NoValue']へ変更という事で良いでしょうか？

2025-01-10 15:08 UTC, Michiko-Ito20 commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
こちらもTrailと同様にデフォルトはnullでした。

2025-01-11 07:16 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
なるほど、ドキュメントは読まれましたか？？
基本的には根拠をAWSの言及から持ってきてほしいので、ドキュメントからの提示を必須と考えてください！


[参考](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-loggingconfiguration.html)

>The name of the bucket where Amazon S3 should store server access log files. You can store log files in any bucket that you own. By default, logs are stored in the bucket where the LoggingConfiguration property is defined.
>（意訳）何も書かない場合は`LoggingConfiguration`を書いたバケットが指定されたものとする

2025-01-13 15:06 UTC, Michiko-Ito20 commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
AWS公式ページによると
＜DestinationBucketName
は、Amazon S3 がサーバーアクセスログファイルを保存するバケットの名前。所有する任意のバケットにログファイルを保存できます。デフォルトでは、ログは LoggingConfigurationプロパティが定義されているバケットに保存されます。
必須: いいえ
タイプ: 文字列
更新に必要なもの:[中断なし]＞
参照:https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-loggingconfiguration.html

AWS::NoValueは特に指定しないという意味。以上のことと、DestinationBucketNameは必須ではなく、無い場合はLoggingConfigurationで定義されてるバケットに保存されるという事なので、今回はハッシュ化して行を無効化します。

2025-01-13 15:26 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
コメント化、ですね！
了解です！

2025-01-13 15:26 UTC, MasatoshiMizumoto commented on CFn_training20241031/Training20241113.yml
> +        DestinationBucketName: !Ref 'AWS::NoValue'
デフォルトはLoggingConfigurationを設定したバケット名、ですね！

2025-01-18 08:03 UTC, Michiko-Ito20 commented
最後に微修正を加えてデプロイ成功しました。※設計書とマネージドコンソールを突合済みです。

2025-01-18 08:05 UTC, MasatoshiMizumoto approved these changes
お疲れさまでした！
LGTM!
![LGTM](https://lgtmoon.herokuapp.com/images/17069)

2025-01-19 03:26 UTC, merged